/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InspectorImport } from './routes/inspector'
import { Route as CollegeloginImport } from './routes/collegelogin'
import { Route as CollegeImport } from './routes/college'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as LoginInspectorImport } from './routes/login/inspector'
import { Route as LoginCollegeImport } from './routes/login/college'

// Create/Update Routes

const InspectorRoute = InspectorImport.update({
  path: '/inspector',
  getParentRoute: () => rootRoute,
} as any)

const CollegeloginRoute = CollegeloginImport.update({
  path: '/collegelogin',
  getParentRoute: () => rootRoute,
} as any)

const CollegeRoute = CollegeImport.update({
  path: '/college',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginInspectorRoute = LoginInspectorImport.update({
  path: '/login/inspector',
  getParentRoute: () => rootRoute,
} as any)

const LoginCollegeRoute = LoginCollegeImport.update({
  path: '/login/college',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeImport
      parentRoute: typeof rootRoute
    }
    '/collegelogin': {
      id: '/collegelogin'
      path: '/collegelogin'
      fullPath: '/collegelogin'
      preLoaderRoute: typeof CollegeloginImport
      parentRoute: typeof rootRoute
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorImport
      parentRoute: typeof rootRoute
    }
    '/login/college': {
      id: '/login/college'
      path: '/login/college'
      fullPath: '/login/college'
      preLoaderRoute: typeof LoginCollegeImport
      parentRoute: typeof rootRoute
    }
    '/login/inspector': {
      id: '/login/inspector'
      path: '/login/inspector'
      fullPath: '/login/inspector'
      preLoaderRoute: typeof LoginInspectorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/college': typeof CollegeRoute
  '/collegelogin': typeof CollegeloginRoute
  '/inspector': typeof InspectorRoute
  '/login/college': typeof LoginCollegeRoute
  '/login/inspector': typeof LoginInspectorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/college': typeof CollegeRoute
  '/collegelogin': typeof CollegeloginRoute
  '/inspector': typeof InspectorRoute
  '/login/college': typeof LoginCollegeRoute
  '/login/inspector': typeof LoginInspectorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/college': typeof CollegeRoute
  '/collegelogin': typeof CollegeloginRoute
  '/inspector': typeof InspectorRoute
  '/login/college': typeof LoginCollegeRoute
  '/login/inspector': typeof LoginInspectorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/college'
    | '/collegelogin'
    | '/inspector'
    | '/login/college'
    | '/login/inspector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/college'
    | '/collegelogin'
    | '/inspector'
    | '/login/college'
    | '/login/inspector'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/college'
    | '/collegelogin'
    | '/inspector'
    | '/login/college'
    | '/login/inspector'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollegeRoute: typeof CollegeRoute
  CollegeloginRoute: typeof CollegeloginRoute
  InspectorRoute: typeof InspectorRoute
  LoginCollegeRoute: typeof LoginCollegeRoute
  LoginInspectorRoute: typeof LoginInspectorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollegeRoute: CollegeRoute,
  CollegeloginRoute: CollegeloginRoute,
  InspectorRoute: InspectorRoute,
  LoginCollegeRoute: LoginCollegeRoute,
  LoginInspectorRoute: LoginInspectorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/college",
        "/collegelogin",
        "/inspector",
        "/login/college",
        "/login/inspector"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/college": {
      "filePath": "college.tsx"
    },
    "/collegelogin": {
      "filePath": "collegelogin.tsx"
    },
    "/inspector": {
      "filePath": "inspector.tsx"
    },
    "/login/college": {
      "filePath": "login/college.tsx"
    },
    "/login/inspector": {
      "filePath": "login/inspector.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
